# Generated by Django 4.2.6 on 2023-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PAID_LEAVE", "Paid Leave"),
                            ("COMPOFF", "Compoff"),
                            ("OPTIONAL LEAVE", "Optional Leave"),
                            ("CASUAL LEAVE", "Casual Leave"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "leave_choice",
                    models.CharField(
                        choices=[
                            ("Full Day", "Full Day Leave"),
                            ("Half Day", "Half Day leave"),
                        ],
                        default="Full Day",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(max_length=500)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
