# Generated by Django 4.2.6 on 2023-10-30 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_alter_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PAID_LEAVE', 'Paid Leave'), ('COMPOFF', 'Compoff'), ('OPTIONAL LEAVE', 'Optional Leave'), ('CASUAL LEAVE', 'Casual Leave')], max_length=50)),
                ('leaveChoice', models.CharField(choices=[('Full Day', 'Full Day Leave'), ('Half Day', 'Half Day leave')], default='Full Day', max_length=50)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('reason', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaveManager', to='users.employee')),
            ],
        ),
    ]
