# Generated by Django 4.2.6 on 2023-10-30 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employee_joining_date_and_more'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employee'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaveManager', to='users.employee'),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50, null=True),
        ),
    ]
