# Generated by Django 4.2.6 on 2023-11-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0002_remove_leavebalance_leave"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavebalance",
            name="leave_allowed",
        ),
        migrations.AddField(
            model_name="employeeleave",
            name="leave_allowed",
            field=models.IntegerField(default=18),
        ),
    ]
