# Generated by Django 4.2.6 on 2023-10-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_employeeleave_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='reason',
            field=models.TextField(max_length=500),
        ),
    ]
