# Generated by Django 4.2.6 on 2023-11-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
