# Generated by Django 4.2.6 on 2023-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_employeeleave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavebalance',
            name='leaves_allowed',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_allowed',
            field=models.IntegerField(default=18),
        ),
    ]
