# Generated by Django 4.2.6 on 2023-11-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0003_remove_leavebalance_leave_allowed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeleave",
            name="leave_allowed",
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="leave_allowed",
            field=models.IntegerField(default=0),
        ),
    ]
