# Generated by Django 4.2.6 on 2023-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_employeeleave_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleave',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
