# Generated by Django 4.2.6 on 2023-11-18 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0004_remove_employeeleave_leave_allowed_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LeaveBalance",
        ),
    ]
