# Generated by Django 4.2.6 on 2023-11-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_profile_pic'),
        ('leave', '0004_remove_leavebalance_leaves_allowed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeleave',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='leaveChoice',
            new_name='leave_choice',
        ),
        migrations.RenameField(
            model_name='employeeleave',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_remain',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_taken',
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_manager', to='users.employee'),
        ),
    ]
