# Generated by Django 4.2.6 on 2023-11-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0005_delete_leavebalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeleave",
            name="month",
            field=models.DateField(null=True),
        ),
    ]
