# Generated by Django 4.2.6 on 2023-11-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0007_remove_employeeleave_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeleave",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
