# Generated by Django 4.2.6 on 2023-10-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('technologies', models.CharField(choices=[('PYTHON', 'Python'), ('DJANGO', 'Django'), ('JAVASCRIPT', 'JavaScript')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.technology'),
        ),
    ]
