# Generated by Django 4.2.6 on 2023-11-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="annual_leave",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
