# Generated by Django 4.2.6 on 2023-11-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="joining_date",
            field=models.DateField(null=True),
        ),
    ]
