# Generated by Django 4.2.6 on 2023-10-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_proof',
            field=models.CharField(choices=[('ADHAR CARD', 'Adhar Card'), ('PAN CARD', 'Pan Card'), ('DRIVING LICENSE', 'Driving License')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Id_proof',
        ),
    ]
