# Generated by Django 4.2.6 on 2023-10-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_zip_code_employee_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_proof',
            field=models.CharField(choices=[('ADHAR CARD', 'Adhar Card'), ('PAN CARD', 'Pan Card'), ('DRIVING LICENSE', 'Driving License')], max_length=50, null=True),
        ),
    ]
