# Generated by Django 4.2.6 on 2023-10-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='file',
        ),
        migrations.AddField(
            model_name='employee',
            name='id_proof_file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
