# Generated by Django 4.2.6 on 2023-10-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='technology',
            field=models.ManyToManyField(null=True, to='users.technology'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='year_of_experience',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
