# Generated by Django 4.2.6 on 2023-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=50)),
                ("project", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("PROCESSING", "Processing"),
                            ("HOLD", "Hold"),
                            ("TESTING", "Testing"),
                            ("DEPLOYED", "Deployed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("estimate_date", models.DateField()),
                ("file_attachment", models.FileField(upload_to="documents/")),
            ],
        ),
    ]
