# Generated by Django 4.2.6 on 2023-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("COMPLETED", "Completed"),
                    ("PROCESSING", "Processing"),
                    ("HOLD", "Hold"),
                    ("TESTING", "Testing"),
                    ("DEPLOYED", "Deployed"),
                ],
                default="Hold",
                max_length=20,
            ),
        ),
    ]
