# Generated by Django 4.2.6 on 2023-11-18 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salaryslipgeneration",
            name="gross_salary",
        ),
        migrations.RemoveField(
            model_name="salaryslipgeneration",
            name="net_salary",
        ),
        migrations.RemoveField(
            model_name="salaryslipgeneration",
            name="salary_deduction",
        ),
    ]
