# Generated by Django 4.2.6 on 2023-11-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0003_salaryslipgeneration_gross_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryslipgeneration",
            name="payslip_generation_date",
            field=models.DateTimeField(null=True),
        ),
    ]
