# Generated by Django 4.2.6 on 2023-11-19 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0004_alter_salaryslipgeneration_salary_deduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryslipgeneration",
            name="payslip_generation_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
