# Generated by Django 4.2.6 on 2023-11-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0006_alter_salaryslipgeneration_salary_deduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="salaryslipgeneration",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Payment Status"),
        ),
        migrations.AddField(
            model_name="salaryslipgeneration",
            name="stripe_payment_intent",
            field=models.CharField(default=False, max_length=200),
        ),
    ]
