# Generated by Django 4.2.6 on 2023-11-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('checkInTime', models.TimeField()),
                ('checkOutTime', models.TimeField(null=True)),
                ('startBreakTime', models.TimeField(null=True)),
                ('endBreakTime', models.TimeField(null=True)),
                ('totalHoursWorked', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
