# Generated by Django 4.2.6 on 2023-11-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_totalworkinghours_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalworkinghours',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
