# Generated by Django 4.2.6 on 2023-11-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='totalHoursWorked',
        ),
    ]
