# Generated by Django 4.2.6 on 2023-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkOutTime',
            field=models.DateTimeField(null=True),
        ),
    ]
