# Generated by Django 4.2.6 on 2023-11-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_totalhoursworked'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='totalHoursWorked',
            field=models.DurationField(null=True),
        ),
    ]
