# Generated by Django 4.2.6 on 2023-11-17 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("attendance", "0003_totalworkinghours_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TotalWorkingHours",
            new_name="DailyWorkingHours",
        ),
    ]
