# Generated by Django 4.2.6 on 2023-10-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_checkouttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkInTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='checkOutTime',
            field=models.TimeField(null=True),
        ),
    ]
