# Generated by Django 4.2.6 on 2023-10-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_checkintime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkInTime',
            field=models.TimeField(null=True),
        ),
    ]
